### ISSUE TITLE
protobuf file generation broken

### ISSUE THREAD

**Issue by natevecc** [frees-io/sbt-frees-protogen#24]
I think this [line](https://github.com/frees-io/sbt-freestyle-protogen/blob/master/core/src/main/scala/proto/converters.scala#L132) is causing my protobuf files to be generated without the rpc calls in the service body.
```protobuf
service IdentityService {
   // methods are not here :(
}
```
I think this is because the `@rpc` annotation changed to take a value and the macro hasn't been updated to account for this.

If I downgrade to free-rpc 0.2.0 before the value was added to the rpc annotation the file is generated correctly.

**Comment by juanpedromoreno** [comment]
Thanks for reporting this @natevecc .

We need to upgrade this plugin according to the latest changes introduced in `frees-rpc`.
